# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Link otomatik alinir lutfen degistirmeyiniz,', max_length=80, null=True),
        ),
    ]
