# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(default=''),
        ),
    ]
