# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='BlogVideo/x.mp4', upload_to='BlogVideo'),
        ),
    ]
