# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180314_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='okunmasayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='BlogVideo'),
        ),
    ]
